### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by MTSnacks** [anomaly256/neon-syntax#4]
In index.less: Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by Psylocybit** [comment]
Hello @MTSnacks, I also ran into this issue. The fix was very simple.

Just required changing the base.less file adequately and renaming the `.editor` class keyword to the [recommended](https://atom.io/docs/latest/upgrading/upgrading-your-syntax-theme) `atom-text-editor` selector keyword.

I pushed a fix for this issue, check [Psylocybit/neon-syntax](https://github.com/Psylocybit/neon-syntax).

**Comment by anomaly256** [comment]
Merged, packaged, and deployed, thanks again
